language: c

sudo: required

script:
  - autoreconf -iv
  - ./configure
  - make chec

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

notifications:
  email: false

matrix:
  allow_failures:
    - os: osx

