language: c

sudo: required

script:
  - uname -s && python -V
  - autoreconf -iv
  - ./configure
  - make check
  - cd test
  - make
  #- sudo pip install enum
  - pip install -r requirements.txt
  - ls -lA
  - python test.py

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

notifications:
  email: false

matrix:
  allow_failures:
    - os: osx

