language: c

sudo: required

script:
  - uname -o
  - autoreconf -iv
  - ./configure
  - make check
  - cd test
  - make

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

notifications:
  email: false

matrix:
  allow_failures:
    - os: osx

