language: c

sudo: required

script:
  - uname -s
  - autoreconf -iv
  - ./configure
  - make check
  - cd test
  - make
  - sudo pip install enum
  - ls -lA
  - python test.py

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

notifications:
  email: false

matrix:
  allow_failures:
    - os: osx

